# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Yoann Poupart"
description: "Personal website, blog & portfolio"
email: yoann.poupart@ens-lyon.org
baseurl: "" # the subpath of your site, e.g. /blog
domain: yp-edu.github.io
url: "https://yp-edu.github.io" #"http://192.168.1.184:4000" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/images/logo.png
github:
  is_project_page: false
  is_user_page: true
  owner_name: Xmaster6y
  owner_url: "https://github.com/Xmaster6y/"
  repo_url: "https://github.com/yp-edu/yp-edu.github.io"
  version: 1.0.0
linkedin:
  url: "https://www.linkedin.com/in/yoann-poupart"


# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist

# Markdown settings
markdown: CustomMarkProcessor

# Defaults
defaults:
  - scope:
      path: ''
    values:
      layout: 'listing'
  - scope:
      path: ''
      type: 'tags'
    values:
      layout: 'tag-listing'
  - scope:
      path: ''
      type: 'stories'
    values:
      layout: 'story'
  - scope:
      path: ''
      type: 'projects'
    values:
      layout: 'story'
  - scope:
      path: ''
      type: 'articles'
    values:
      layout: 'story'
  - scope:
      path: ''
      type: 'drafts'
    values:
      layout: 'story'
  - scope:
      path: ''
      type: 'publications'
    values:
      layout: 'publication'

# Collections
collections_dir: pages
collections:
  stories:
    output: true
    permalink: /:collection/:title
  projects:
    output: true
    permalink: /:collection/:title
  articles:
    output: true
    permalink: /:collection/:title
  tags:
    output: true
    permalink: /:collection/:title
  drafts:
    output: true
    permalink: /:collection/:title
  publications:
    output: true
    permalink: /:collection/:title

feed:
  collections:
    stories:
      path: /stories/feed.xml
    projects:
      path: /projects/feed.xml
    articles:
      path: /articles/feed.xml
